### ISSUE TITLE
New Component Request: Resizable Windows/Popups  

### ISSUE THREAD

**Issue by theakatz** [infor-design/design-system#105] opened 2018-04-04 15:44 UTC
OG Tickets: 
- https://jira/browse/SOHO-6694 
- https://jira.infor.com/browse/UXD-252
- https://jira.infor.com/browse/UXD-80

**Comment by theakatz** [comment] 2018-10-31 19:46
@kayiuho we need design to take a look before handing off to enterprise devs, can you please?

**Comment by tmcconechy** [comment] 2018-11-01 12:12
Just to add there is also a request for resizing the editor. So i think the same resize grip could be used on the bottom corner of http://master-enterprise.demo.design.infor.com/components/editor/example-index.html as well.

**Comment by kayiuho** [comment] 2018-11-02 21:19
**Modal (including Contextual Action Panel)** – 
• For "resizing" and "movable", are they both getting applied to all modal variations we have as a standard functionality? or just as one variation?
• For "movable", could a mouse cursor change (hot spot on the top area) satisfy the ask? 
• In the case where there are 2 actions/buttons on the bottom of the modal, I don't think having the "resize grip" mark in the bottom right corner "on top" of the action/button is the right answer as it looks confusing and unintentional like a bug. It doesn't seem the resizing is contextual to the "container"/modal, instead it looks like it's something that could control the "button" only because of the visual relationship. I'm exploring this a little more so I'll post some design solutions when I have them.

**Rich Text Editor** –
• For adding the "resize grip" mark, is design needed before dev implementation? or can it be "copied" from the Textarea component?

**Comment by tmcconechy** [comment] 2018-11-05 14:19
- "resizing" and "moving" are going to be options that would not be the default.
- yes i think we would just change cursor over the top portion of the modal. so lets go with that.
- ok , happy to see your solution. Maybe even just a cursor change too?
- yes i think that we can just reuse the same thing, but the problem is some browsers may make this appear a little bit different but can try.

**Comment by kayiuho** [comment] 2018-11-06 19:51
Hey Tim, I'm having other thoughts about making both requests. After digging around in JIRA to find the use cases where these requests came about, I'm not confident that fulfilling the asks is the right answer in solving BI's issue with their current user workflow. Here are some UX issues that would come with having the modals being able to resize and move around on the page:

1) If a user needs to move the modal aside to be able to see what's on the "bottom layer" while changing the data inside the modal, then the modal component itself may not be the most suitable component to use in this workflow. The modal comes with an overlay and by "dimming" it, then it breaks the pattern and we're now allowing future design inconsistency. We also need to understand why users must work that way of having the modal "opened" and reference another set of data that's not available within the modal. If that must be the case, then users may need a different experience all together.

2) If a user needs to resize the modal (generally enlarging it) to view more data, then again, the modal component itself may not be the most suitable component to use in this workflow. IDS does not currently have guidelines on modal sizing, product teams should use their discretion when it comes to sizing modals to fit content properly based on their use cases. If resizing must be the case, then the user experience of having a resizable modal should be re-evaluated all together to make sure we are delivering the most efficient workflow to our users.

3) Keep in mind that these functionalities will not translate well across devices and can be challenging to enforce in small screensize. 

Generally speaking, modals should be used for short, direct dialog exchanges between the system and the user, like requiring or correcting information, and display warnings for users to make critical decisions. It should not be used as a solution for user to interact within a complex workflow.

With that said, our modal guidelines on IDS should be updated accordingly and I'll create an issue to do so.

**Comment by tmcconechy** [comment] 2018-11-06 20:06
I agree fully its not the best patter for UX. Also i saw the active issue in Jira is not linked https://jira.infor.com/browse/UXD-80 there is several watchers there that posted more use cases. Of those i see these two cases mentioned:

- the cases on https://jira.infor.com/browse/IBP-14903 and https://jira.infor.com/browse/IBP-16901 both seem like they should be solved by just being more dynamic in sizing not forcing the user to figure out the actual size.
- plus one use case for:  ability to move the pop-up windows to view some contextual information "underneath"

But, one additional thought is we do have contextual action panels that are by definition more complex interactions. Would we consider it there? We still have the problem of the content being dimmed out, so not so sure its great there either.

Dragging:
I also think that if they need to see something in behind it would be better to either.
- display it on the modal so they can see it without having to manipulate and drag stuff around
- actually default the values in so the user doesnt need to type it

Resize:
- maybe we just need to code the dialog to size more dynamically and not use the user decide this. 

As i see it we have it covered...Im not seeing any great use cases for this that cant be solved a better way.

**Comment by theakatz** [comment] 2018-11-12 16:15
We concluded that this isn’t quite the proper way we want the modal to work in the library so we will not be implementing these requests. Any scenarios that want or need to be updated to handle something similar, we can address on a case-by-case basis by raising a new issue.

**Comment by kevinwhitedesign** [comment] 2020-07-29 15:41
@inforandy @tmcconechy also lost in time

**Comment by tmcconechy** [comment] 2020-07-29 15:43
I tink this is a duplicate of https://github.com/infor-design/enterprise/issues/1140 so will close. We still need to discuss this feature. It seems like a bad pattern that no one likes that everyone still wants.

Suggestion is to push back again. But i dont think it needs much for design if we do decide to do it

**Closed by tmcconechy** 2020-07-29 15:43 UTC
Labels: for: design, type: enhancement :sparkles:
