### ISSUE TITLE
Offer Letter Preview Dialog \ Usability Enhancement to Get Back to Visual View from HTML View

### ISSUE THREAD

**Issue by adinenno** [infor-design/design-system#440] opened 2020-02-04 16:32 UTC
Currently, on the Offer Preview dialog, using the 4.0 controls, once you click HTML, it is not intuitive how you get back to the visual editor. The way that you get back is by clicking the word Visual. I've seen users have NO IDEA that you have to click the word Visual and think they have to commit to Submit.

This can be seen on http://master-enterprise.demo.design.infor.com/components/editor/example-index.html

A usability suggestion is to have some box around the word Visual so it stands out.

Our users are being forced to use the HTML view due to the formatting issues with offer letters so this has come up.

Andrew from Landmark has indicated I need a GIT for changing this.

**Comment by adinenno** [comment] 2020-02-04 16:32
![Offer Letter Preview Visual Option](https://user-images.githubusercontent.com/50713087/73765092-0d9c9280-4742-11ea-8c0d-3e0f1da841bd.gif)
![Visual Offer Letter](https://user-images.githubusercontent.com/50713087/73765110-142b0a00-4742-11ea-82be-d16524baa439.JPG)

**Comment by adinenno** [comment] 2020-02-04 16:33
![Preview Offer Letter](https://user-images.githubusercontent.com/50713087/73765178-2c9b2480-4742-11ea-90dc-86f79f340ffa.JPG)

**Comment by tmcconechy** [comment] 2020-02-04 16:37
I guess that would mean putting boxes on every button. Thats a bit of a large design change. Wonder if using some icon for this instead would help?

**Comment by adinenno** [comment] 2020-02-04 16:40
I am asking Jamie to comment too. Can we have two different links? I definitely think it's confusing for the customer to not know how to get back to Visual from HTML. I've seen a customer be clueless and think they have to exit out of the dialog completely.

**Comment by jamie-norman** [comment] 2020-02-04 18:47
I would not suggest putting boxes around any buttons. I think it's just making sure the user can understand there are two different states and how to get back. Could simply be a wording thing. Off the top head, I wonder about using a switch to show the mode that the user is in.

**Comment by tmcconechy** [comment] 2020-02-04 18:57
Another idea of the top of my head is a toggle button http://latest-enterprise.demo.design.infor.com/components/button/example-toggle-button.html although the (filter in this example) toggle has not got great accessibility with just a color change

**Comment by adinenno** [comment] 2020-02-04 18:59
I agree 100 percent with Jamie's comments that we need to make sure the user can understand there are two different states and how to get back.

**Comment by jamie-norman** [comment] 2020-02-04 19:14
![image](https://user-images.githubusercontent.com/44705854/73778065-2ad85d80-4750-11ea-9c76-8dfd28cc88f7.png)
Thinking something along these lines... still working it out

**Comment by adinenno** [comment] 2020-02-05 15:34
I like what you have here Jamie. The toggle would be fine too.

**Comment by tmcconechy** [comment] 2020-02-05 15:35
My only concern with it is it takes up a lot more space so its likely to overflow the button. Also toolbars dont support switches at the moment so thats more work. I'd like to see other options.

**Comment by jamie-norman** [comment] 2020-02-05 15:41
Yeah, I agree. Like I said, still needs some thought. I'll post other options when I get a chance

**Comment by tmcconechy** [comment] 2020-02-05 15:43
cc @kevinwhitedesign @kentonquatman

**Comment by kentonquatman** [comment] 2020-02-05 16:13
I think the problem is in the state transition. The modal shrinks, all the options disappear, and the visual button moves to the left. Too many changes at once leaves the user disoriented. Could be as simple as keeping the width and making all the other editor options disabled.

**Comment by kentonquatman** [comment] 2020-02-05 16:38
![state-transition](https://user-images.githubusercontent.com/847306/73862044-f3c78200-480b-11ea-8407-4988d7e6416a.gif)
This might be less confusing.

**Comment by jamie-norman** [comment] 2020-02-05 16:42
Agreed Kenton. Didn't even get to that part. That definitely promotes confusion for the user, which I think is part of what Adriana was describing to me. In general, we should maintain modal window sizes when there are multiple states.

**Comment by jamie-norman** [comment] 2020-02-05 16:43
I still think there's opportunity to improve the switch for wysiwyg/code

**Comment by jamie-norman** [comment] 2020-02-05 16:59
What if it appeared more like a tab?

![image](https://user-images.githubusercontent.com/44705854/73864055-9d0b7980-4806-11ea-8af7-ba9a20572d86.png)

**Comment by kentonquatman** [comment] 2020-02-05 17:25
Hmm... that could be interesting. I do like GitHub's text editor. I was just looking at Redactor too:
https://imperavi.com/redactor/
![Screen Shot 2020-02-05 at 12 19 18 PM](https://user-images.githubusercontent.com/847306/73866213-76ebd680-4812-11ea-89bd-0393d8e1ce56.png)
![Screen Shot 2020-02-05 at 12 19 48 PM](https://user-images.githubusercontent.com/847306/73866217-794e3080-4812-11ea-8a70-c0272706f20b.png)
![Screen Shot 2020-02-05 at 12 20 33 PM](https://user-images.githubusercontent.com/847306/73866229-7d7a4e00-4812-11ea-91ae-3a779c01affd.png)

**Comment by jamie-norman** [comment] 2020-02-05 18:07
Nice little "toggled on" state signifier

**Comment by jamie-norman** [comment] 2020-02-05 18:20
Quick mockup:
![image](https://user-images.githubusercontent.com/44705854/73870529-e01f1a00-4811-11ea-9134-4c610ac9ef57.png)

**Comment by kentonquatman** [comment] 2020-02-05 18:26
Since this issue is related to a specific application of the rich text editor inside a modal, I've started a new issue for general updates to the component: #441

**Comment by kentonquatman** [comment] 2020-02-05 20:58
Closing this with the recommendation to avoid resizing the rich text editor when switching between visual and HTML modes. Enhancements to the RTE component are being tracked in issue #441.

**Closed by kentonquatman** 2020-02-05 20:58 UTC
Labels: for: design, team: landmark
