### ISSUE TITLE
Compact form: additional requirements

### ISSUE THREAD

**Issue by nickwynja** [infor-design/design-system#370] opened 2019-04-15 14:18 UTC
We need to plan for some additional design requirements of the compact forms. This might include:

* Clearer separate between groupings
* Handling several errors at the same time [\[Example\]](http://master-enterprise.demo.design.infor.com/components/validation/test-message-types.html)
* A combined `[ key | description ]` field [\[Example\]](https://user-images.githubusercontent.com/1012017/58206639-18e08880-7caf-11e9-9976-806758489466.png)
* Ability to open input action buttons like date picker with keyboard action
* Error, required, dirty etc. states using icon with shape

**Comment by kayiuho** [comment] 2019-06-12 19:09
Work-in-process designs are posted here:
https://paper.dropbox.com/doc/Compact-Form--AdQOsMg9ysFNqD9ePAL2y7agAQ-R8idPCwaQcbGBbIZVX3Md (internal H&L link)

**Comment by EdwardCoyle** [comment] 2019-06-14 15:53
@kayiuho, I've updated the working branch on infor-design/enterprise#2193 to modify what's already finished to reflect V5 of the designs on Dropbox.

I was wondering if you've been working on Uplift designs for the Compact form as well?  Overall, the Uplift theme has different font sizes for text/labels, padding/margins, etc that I think we'd need to account for.

Currently, switching to Uplift on the Compact Form looks like:
![Screen Shot 2019-06-14 at 11 47 16 AM](https://user-images.githubusercontent.com/3249601/59521746-08c95c80-8e9b-11e9-8ab8-38e54bf84cae.png)

**Comment by kayiuho** [comment] 2019-06-18 16:13
@nickwynja they're all just design options that I was exploring, I do like when there's spacing in between the sections. @EdwardCoyle would it be a problem adding the spacing back?

**Comment by kayiuho** [comment] 2019-06-18 16:23
@EdwardCoyle what do you mean by "Uplift designs for the Compact form"?

**Comment by EdwardCoyle** [comment] 2019-07-01 13:36
Just noting - all the designs on the Dropbox Paper document are based on the Soho style.  We should look at implementing the Uplift style against it as well.

**Comment by nickwynja** [comment] 2019-07-01 15:52
@EdwardCoyle The designs were planned to be "soho" since they would generally roll out and be available to people who haven't adopted the uplift theme yet.

What kind of differences do you expect needing that aren't just "out of the box" when someone switches to the uplift theme for the compact form?

**Comment by EdwardCoyle** [comment] 2019-07-01 16:12
Mostly my concerns are around typography and spacing.  The V5 design in the Dropbox doc shrinks the fonts back down to the "standard" form field sizes that would exist on a normal input field.  In Uplift, the font size for labels is larger, and the line heights for Source Sans are a bit different.  We already maintain a stylesheet for Uplift Compact Form, so ideally I'd like to get those nailed down.

Also wondering if we ever came to conclusions about the experimental styles for dirty indicators, required fields, etc?  I think we shouldn't change those from what we currently ship, but I know those designs weren't finalized either.

**Comment by benfenton** [comment] 2019-08-22 13:06
<img width="1320" alt="3 5_vs_4 0_form_example" src="https://user-images.githubusercontent.com/121309/63516912-f59ac480-c4bb-11e9-944d-21f5c41382e9.png">
This is an example of a pain point we're seeing with the current switch from 3.5 to 4.0 @EdwardCoyle This might be a good one to reproduce in a demo to see if we can get a comparable number of fields on the screen without a user having to scroll.

**Comment by EdwardCoyle** [comment] 2019-08-22 14:44
@benfenton Just to clarify, we would take the contents of this form and trying to apply them to a Compact Form layout, [such as this one](http://master-enterprise.demo.design.infor.com/components/form-compact/example-index.html?theme=uplift)?

**Comment by benfenton** [comment] 2019-08-22 14:46
Yeah, it could be a good use case for the demo of this form, since currently Infor is pushing back on this form in 4.x because it's too much scrolling.

**Comment by kentonquatman** [comment] 2020-01-10 16:03
Closing this as it's being addressed by enterprise issue #3249
https://github.com/infor-design/enterprise/issues/3249

**Closed by kentonquatman** 2020-01-10 16:03 UTC
Labels: [3], for: design, type: enhancement :sparkles:
